title: Raul Pinedo Z.
logo: /assets/images/IMG_20231001_121358.jpg
description: Enteprise IT Engineer, PC Gaming Enthusiast
show_downloads: true
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
