title: Raul Pinedo Z.
logo: /assets/img/my-linkedin-pic.jpg
description: Enteprise IT Engineer, PC Gaming Enthusiast
show_downloads: true
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
